import { Review, Comment } from '@/types';
import { getAvatarUrl } from '@/lib/utils/avatar';

export const initialReviews: Review[] = [
  {
    id: 'review-1',
    productId: '1',
    userId: 'user-1',
    userName: 'Sarah Johnson',
    avatar: getAvatarUrl('Sarah Johnson'),
    rating: 5,
    comment:
      "Absolutely love this chair! It's comfortable, stylish, and perfect for my home office. The quality is excellent and it arrived quickly.",
    date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'review-2',
    productId: '1',
    userId: 'user-2',
    userName: 'Michael Chen',
    avatar: getAvatarUrl('Michael Chen'),
    rating: 4,
    comment:
      'Great chair overall. Very comfortable for long work sessions. The only minor issue is that assembly took a bit longer than expected.',
    date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'review-3',
    productId: '1',
    userId: 'user-3',
    userName: 'Emily Rodriguez',
    avatar: getAvatarUrl('Emily Rodriguez'),
    rating: 5,
    comment:
      'Perfect addition to my living room! The design is modern and it matches perfectly with my decor. Highly recommend!',
    date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'review-4',
    productId: '1',
    userId: 'user-4',
    userName: 'David Kim',
    avatar: getAvatarUrl('David Kim'),
    rating: 4,
    comment:
      'Good quality chair at a reasonable price. The cushion is comfortable and the frame feels sturdy. Would buy again.',
    date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'review-5',
    productId: '1',
    userId: 'user-5',
    userName: 'Lisa Anderson',
    avatar: getAvatarUrl('Lisa Anderson'),
    rating: 5,
    comment:
      'Exceeded my expectations! The chair is beautiful, well-made, and incredibly comfortable. Customer service was also excellent.',
    date: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const initialComments: Comment[] = [
  {
    id: 'comment-1',
    productId: '1',
    userId: 'user-6',
    userName: 'James Wilson',
    avatar: getAvatarUrl('James Wilson'),
    text: 'Does this chair come in other colors? I love the design but would prefer a darker shade.',
    date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    replies: [
      {
        id: 'reply-1',
        productId: '1',
        userId: 'admin-1',
        userName: 'Funiro Support',
        avatar: getAvatarUrl('Funiro Support'),
        text: 'Hi James! Yes, this chair is available in black, gray, and beige. Check our product page for all color options.',
        date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000 + 3600000).toISOString(),
      },
    ],
  },
  {
    id: 'comment-2',
    productId: '1',
    userId: 'user-7',
    userName: 'Maria Garcia',
    avatar: getAvatarUrl('Maria Garcia'),
    text: 'How long does shipping usually take? I need this for an event next week.',
    date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    replies: [],
  },
  {
    id: 'comment-3',
    productId: '1',
    userId: 'user-8',
    userName: 'Robert Taylor',
    avatar: getAvatarUrl('Robert Taylor'),
    text: 'Is assembly required or does it come pre-assembled?',
    date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    replies: [
      {
        id: 'reply-2',
        productId: '1',
        userId: 'user-9',
        userName: 'Alex Thompson',
        avatar: getAvatarUrl('Alex Thompson'),
        text: 'It requires minimal assembly - took me about 10 minutes. Very straightforward!',
        date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000 + 7200000).toISOString(),
      },
    ],
  },
  {
    id: 'comment-4',
    productId: '1',
    userId: 'user-10',
    userName: 'Jennifer Lee',
    avatar: getAvatarUrl('Jennifer Lee'),
    text: "What's the weight capacity for this chair?",
    date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    replies: [],
  },
  {
    id: 'comment-5',
    productId: '1',
    userId: 'user-11',
    userName: 'Christopher Brown',
    avatar: getAvatarUrl('Christopher Brown'),
    text: "Can I return this if it doesn't fit my space? What's the return policy?",
    date: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    replies: [],
  },
  {
    id: 'comment-6',
    productId: '1',
    userId: 'user-12',
    userName: 'Amanda White',
    avatar: getAvatarUrl('Amanda White'),
    text: 'Love the design! Does it come with a warranty?',
    date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    replies: [
      {
        id: 'reply-3',
        productId: '1',
        userId: 'admin-2',
        userName: 'Funiro Support',
        avatar: getAvatarUrl('Funiro Support'),
        text: 'Yes! All our products come with a 1-year warranty covering manufacturing defects.',
        date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000 + 1800000).toISOString(),
      },
    ],
  },
  {
    id: 'comment-7',
    productId: '1',
    userId: 'user-13',
    userName: 'Daniel Martinez',
    avatar: getAvatarUrl('Daniel Martinez'),
    text: 'Is the cushion removable for cleaning?',
    date: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    replies: [],
  },
  {
    id: 'comment-8',
    productId: '1',
    userId: 'user-14',
    userName: 'Nicole Davis',
    avatar: getAvatarUrl('Nicole Davis'),
    text: 'Perfect for my home office! The ergonomics are great for long work days.',
    date: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    replies: [],
  },
  {
    id: 'comment-9',
    productId: '1',
    userId: 'user-15',
    userName: 'Kevin Johnson',
    avatar: getAvatarUrl('Kevin Johnson'),
    text: 'How does this compare to the premium version? Is the price difference worth it?',
    date: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
    replies: [],
  },
  {
    id: 'comment-10',
    productId: '1',
    userId: 'user-16',
    userName: 'Rachel Green',
    avatar: getAvatarUrl('Rachel Green'),
    text: "The chair looks amazing in person! The photos don't do it justice. Highly recommend!",
    date: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    replies: [
      {
        id: 'reply-4',
        productId: '1',
        userId: 'user-17',
        userName: 'Tom Wilson',
        avatar: getAvatarUrl('Tom Wilson'),
        text: 'I totally agree! The quality is much better than expected.',
        date: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000 + 14400000).toISOString(),
      },
    ],
  },
];
